/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */
package org.apache.cordova;

public final class R {
	public static final class array {
		public static final int xwalk_resources_list = 0x7f0c0000;
	}
	public static final class attr {
		public static final int select_dialog_multichoice = 0x7f010017;
		public static final int select_dialog_singlechoice = 0x7f010018;
	}
	public static final class color {
		public static final int color_picker_background_color = 0x7f09000c;
		public static final int color_picker_border_color = 0x7f09000b;
		public static final int dropdown_dark_divider_color = 0x7f09000e;
		public static final int dropdown_divider_color = 0x7f09000d;
	}
	public static final class dimen {
		public static final int color_button_height = 0x7f08001f;
		public static final int color_picker_gradient_margin = 0x7f08001e;
		public static final int config_min_scaling_span = 0x7f080022;
		public static final int config_min_scaling_touch_major = 0x7f080023;
		public static final int dropdown_item_divider_height = 0x7f080021;
		public static final int dropdown_item_height = 0x7f080020;
		public static final int link_preview_overlay_radius = 0x7f08001d;
	}
	public static final class drawable {
		public static final int bubble = 0x7f020000;
		public static final int bubble_arrow_up = 0x7f020001;
		public static final int color_button_background = 0x7f020002;
		public static final int color_picker_advanced_select_handle = 0x7f020003;
		public static final int color_picker_border = 0x7f020004;
		public static final int dropdown_popup_background = 0x7f020034;
		public static final int dropdown_popup_background_down = 0x7f020035;
		public static final int dropdown_popup_background_up = 0x7f020036;
		public static final int ic_menu_search_holo_light = 0x7f02003a;
		public static final int ic_menu_share_holo_light = 0x7f02003b;
		public static final int icon = 0x7f02003c;
		public static final int ondemand_overlay = 0x7f02003d;
		public static final int pageinfo_warning_major = 0x7f02003e;
		public static final int splash = 0x7f020040;
	}
	public static final class id {
		public static final int ampm = 0x7f070041;
		public static final int appView = 0x7f07003a;
		public static final int arrow_image = 0x7f070048;
		public static final int color_button_swatch = 0x7f07004b;
		public static final int color_picker_advanced = 0x7f070011;
		public static final int color_picker_simple = 0x7f070012;
		public static final int date_picker = 0x7f070032;
		public static final int date_time_suggestion = 0x7f070034;
		public static final int date_time_suggestion_label = 0x7f070036;
		public static final int date_time_suggestion_value = 0x7f070035;
		public static final int dropdown_label = 0x7f070038;
		public static final int dropdown_menu_text = 0x7f070037;
		public static final int dropdown_popup_window = 0x7f07000c;
		public static final int dropdown_sublabel = 0x7f070039;
		public static final int gradient = 0x7f07000f;
		public static final int gradient_border = 0x7f07000e;
		public static final int hour = 0x7f07003b;
		public static final int icon_view = 0x7f070046;
		public static final int main_text = 0x7f070049;
		public static final int milli = 0x7f070040;
		public static final int minute = 0x7f07003c;
		public static final int more_colors_button = 0x7f070014;
		public static final int more_colors_button_border = 0x7f070013;
		public static final int pickers = 0x7f070042;
		public static final int position_in_year = 0x7f070043;
		public static final int second = 0x7f07003e;
		public static final int second_colon = 0x7f07003d;
		public static final int second_dot = 0x7f07003f;
		public static final int seek_bar = 0x7f070010;
		public static final int select_action_menu_copy = 0x7f07004e;
		public static final int select_action_menu_cut = 0x7f07004d;
		public static final int select_action_menu_paste = 0x7f07004f;
		public static final int select_action_menu_select_all = 0x7f07004c;
		public static final int select_action_menu_share = 0x7f070050;
		public static final int select_action_menu_web_search = 0x7f070051;
		public static final int selected_color_view = 0x7f070017;
		public static final int selected_color_view_border = 0x7f070016;
		public static final int sub_text = 0x7f07004a;
		public static final int text = 0x7f07000d;
		public static final int text_wrapper = 0x7f070047;
		public static final int time_picker = 0x7f070033;
		public static final int title = 0x7f070015;
		public static final int top_view = 0x7f070045;
		public static final int year = 0x7f070044;
	}
	public static final class layout {
		public static final int color_picker_advanced_component = 0x7f040000;
		public static final int color_picker_dialog_content = 0x7f040001;
		public static final int color_picker_dialog_title = 0x7f040002;
		public static final int date_time_picker_dialog = 0x7f040012;
		public static final int date_time_suggestion = 0x7f040013;
		public static final int dropdown_item = 0x7f040014;
		public static final int main = 0x7f040015;
		public static final int multi_field_time_picker_dialog = 0x7f040016;
		public static final int two_field_date_picker = 0x7f040017;
		public static final int validation_message_bubble = 0x7f040018;
	}
	public static final class menu {
		public static final int select_action_menu = 0x7f0d0000;
	}
	public static final class mipmap {
		public static final int app_icon = 0x7f030000;
	}
	public static final class raw {
		public static final int contacts_api = 0x7f060000;
		public static final int device_capabilities_api = 0x7f060001;
		public static final int icudtl = 0x7f060002;
		public static final int launch_screen_api = 0x7f060003;
		public static final int messaging_api = 0x7f060004;
		public static final int presentation_api = 0x7f060005;
		public static final int xwalk = 0x7f060006;
	}
	public static final class string {
		public static final int accessibility_content_view = 0x7f0a001f;
		public static final int accessibility_date_picker_month = 0x7f0a002f;
		public static final int accessibility_date_picker_week = 0x7f0a0030;
		public static final int accessibility_date_picker_year = 0x7f0a0031;
		public static final int accessibility_datetime_picker_date = 0x7f0a002d;
		public static final int accessibility_datetime_picker_time = 0x7f0a002e;
		public static final int accessibility_time_picker_ampm = 0x7f0a0036;
		public static final int accessibility_time_picker_hour = 0x7f0a0032;
		public static final int accessibility_time_picker_milli = 0x7f0a0035;
		public static final int accessibility_time_picker_minute = 0x7f0a0033;
		public static final int accessibility_time_picker_second = 0x7f0a0034;
		public static final int actionbar_share = 0x7f0a001d;
		public static final int actionbar_web_search = 0x7f0a001e;
		public static final int app_name = 0x7f0a0063;
		public static final int color_picker_button_black = 0x7f0a004f;
		public static final int color_picker_button_blue = 0x7f0a004b;
		public static final int color_picker_button_cancel = 0x7f0a0047;
		public static final int color_picker_button_cyan = 0x7f0a004a;
		public static final int color_picker_button_green = 0x7f0a004c;
		public static final int color_picker_button_magenta = 0x7f0a004d;
		public static final int color_picker_button_more = 0x7f0a0042;
		public static final int color_picker_button_red = 0x7f0a0049;
		public static final int color_picker_button_set = 0x7f0a0046;
		public static final int color_picker_button_white = 0x7f0a0050;
		public static final int color_picker_button_yellow = 0x7f0a004e;
		public static final int color_picker_dialog_title = 0x7f0a0048;
		public static final int color_picker_hue = 0x7f0a0043;
		public static final int color_picker_saturation = 0x7f0a0044;
		public static final int color_picker_value = 0x7f0a0045;
		public static final int copy_to_clipboard_failure_message = 0x7f0a0051;
		public static final int cpu_arch_mismatch_message = 0x7f0a0060;
		public static final int cpu_arch_mismatch_title = 0x7f0a005f;
		public static final int date_picker_dialog_clear = 0x7f0a0022;
		public static final int date_picker_dialog_other_button_label = 0x7f0a0023;
		public static final int date_picker_dialog_set = 0x7f0a0021;
		public static final int date_picker_dialog_title = 0x7f0a0020;
		public static final int date_time_picker_dialog_title = 0x7f0a0024;
		public static final int download_already_exists_toast = 0x7f0a0057;
		public static final int download_failed_toast = 0x7f0a0058;
		public static final int download_finished_toast = 0x7f0a0059;
		public static final int download_no_permission_toast = 0x7f0a0056;
		public static final int download_start_toast = 0x7f0a0055;
		public static final int go = 0x7f0a0064;
		public static final int goto_store_button_label = 0x7f0a0061;
		public static final int http_auth_log_in = 0x7f0a005e;
		public static final int http_auth_password = 0x7f0a005d;
		public static final int http_auth_title = 0x7f0a005b;
		public static final int http_auth_user_name = 0x7f0a005c;
		public static final int js_alert_title = 0x7f0a0052;
		public static final int js_confirm_title = 0x7f0a0053;
		public static final int js_prompt_title = 0x7f0a0054;
		public static final int low_memory_error = 0x7f0a0040;
		public static final int media_player_error_button = 0x7f0a003a;
		public static final int media_player_error_text_invalid_progressive_playback = 0x7f0a0038;
		public static final int media_player_error_text_unknown = 0x7f0a0039;
		public static final int media_player_error_title = 0x7f0a0037;
		public static final int media_player_loading_video = 0x7f0a003b;
		public static final int month_picker_dialog_title = 0x7f0a002b;
		public static final int opening_file_error = 0x7f0a0041;
		public static final int profiler_error_toast = 0x7f0a003f;
		public static final int profiler_no_storage_toast = 0x7f0a003e;
		public static final int profiler_started_toast = 0x7f0a003c;
		public static final int profiler_stopped_toast = 0x7f0a003d;
		public static final int report_feedback_button_label = 0x7f0a0062;
		public static final int ssl_alert_title = 0x7f0a005a;
		public static final int time_picker_dialog_am = 0x7f0a0026;
		public static final int time_picker_dialog_hour_minute_separator = 0x7f0a0028;
		public static final int time_picker_dialog_minute_second_separator = 0x7f0a0029;
		public static final int time_picker_dialog_pm = 0x7f0a0027;
		public static final int time_picker_dialog_second_subsecond_separator = 0x7f0a002a;
		public static final int time_picker_dialog_title = 0x7f0a0025;
		public static final int week_picker_dialog_title = 0x7f0a002c;
	}
	public static final class style {
		public static final int DropdownPopupWindow = 0x7f0b0004;
		public static final int SelectPopupDialog = 0x7f0b0003;
	}
	public static final class xml {
		public static final int config = 0x7f050000;
	}
}
