/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.ionicframework.goodmood362235;

public final class R {
    public static final class array {
        public static final int xwalk_resources_list=0x7f0c0000;
    }
    public static final class attr {
        /** <p>Must be one of the following constant values.</p>
<table>
<colgroup align="left" />
<colgroup align="left" />
<colgroup align="left" />
<tr><th>Constant</th><th>Value</th><th>Description</th></tr>
<tr><td><code>bottom</code></td><td>0</td><td> Keep in sync with Enums in LikeView </td></tr>
<tr><td><code>inline</code></td><td>1</td><td></td></tr>
<tr><td><code>top</code></td><td>2</td><td></td></tr>
</table>
         */
        public static final int auxiliary_view_position=0x7f010015;
        /** <p>Must be a boolean value, either "<code>true</code>" or "<code>false</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int confirm_logout=0x7f01000c;
        /** <p>Must be a reference to another resource, in the form "<code>@[+][<i>package</i>:]<i>type</i>:<i>name</i></code>"
or to a theme attribute in the form "<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>".
         */
        public static final int done_button_background=0x7f010006;
        /** <p>Must be a string value, using '\\;' to escape characters such as '\\n' or '\\uxxxx' for a unicode character.
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int done_button_text=0x7f010004;
        /** <p>Must be a string value, using '\\;' to escape characters such as '\\n' or '\\uxxxx' for a unicode character.
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int extra_fields=0x7f010001;
        /** <p>Must be a boolean value, either "<code>true</code>" or "<code>false</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int fetch_user_info=0x7f01000d;
        /** <p>Must be a color value, in the form of "<code>#<i>rgb</i></code>", "<code>#<i>argb</i></code>",
"<code>#<i>rrggbb</i></code>", or "<code>#<i>aarrggbb</i></code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int foreground_color=0x7f010012;
        /** <p>Must be one of the following constant values.</p>
<table>
<colgroup align="left" />
<colgroup align="left" />
<colgroup align="left" />
<tr><th>Constant</th><th>Value</th><th>Description</th></tr>
<tr><td><code>center</code></td><td>0</td><td> Keep in sync with Enums in LikeView </td></tr>
<tr><td><code>left</code></td><td>1</td><td></td></tr>
<tr><td><code>right</code></td><td>2</td><td></td></tr>
</table>
         */
        public static final int horizontal_alignment=0x7f010016;
        /** <p>Must be a boolean value, either "<code>true</code>" or "<code>false</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int is_cropped=0x7f010011;
        /** <p>Must be a string value, using '\\;' to escape characters such as '\\n' or '\\uxxxx' for a unicode character.
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int login_text=0x7f01000e;
        /** <p>Must be a string value, using '\\;' to escape characters such as '\\n' or '\\uxxxx' for a unicode character.
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int logout_text=0x7f01000f;
        /** <p>Must be a boolean value, either "<code>true</code>" or "<code>false</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int multi_select=0x7f010007;
        /** <p>Must be a string value, using '\\;' to escape characters such as '\\n' or '\\uxxxx' for a unicode character.
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int object_id=0x7f010013;
        /** <p>Must be one of the following constant values.</p>
<table>
<colgroup align="left" />
<colgroup align="left" />
<colgroup align="left" />
<tr><th>Constant</th><th>Value</th><th>Description</th></tr>
<tr><td><code>small</code></td><td>-2</td><td> Keep in sync with constants in ProfilePictureView </td></tr>
<tr><td><code>normal</code></td><td>-3</td><td></td></tr>
<tr><td><code>large</code></td><td>-4</td><td></td></tr>
</table>
         */
        public static final int preset_size=0x7f010010;
        /** <p>Must be an integer value, such as "<code>100</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int radius_in_meters=0x7f010008;
        /** <p>Must be an integer value, such as "<code>100</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int results_limit=0x7f010009;
        /** <p>Must be a string value, using '\\;' to escape characters such as '\\n' or '\\uxxxx' for a unicode character.
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int search_text=0x7f01000a;
        /** <p>Must be a reference to another resource, in the form "<code>@[+][<i>package</i>:]<i>type</i>:<i>name</i></code>"
or to a theme attribute in the form "<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>".
         */
        public static final int select_dialog_multichoice=0x7f010017;
        /** <p>Must be a reference to another resource, in the form "<code>@[+][<i>package</i>:]<i>type</i>:<i>name</i></code>"
or to a theme attribute in the form "<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>".
         */
        public static final int select_dialog_singlechoice=0x7f010018;
        /** <p>Must be a boolean value, either "<code>true</code>" or "<code>false</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int show_pictures=0x7f010000;
        /** <p>Must be a boolean value, either "<code>true</code>" or "<code>false</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int show_search_box=0x7f01000b;
        /** <p>Must be a boolean value, either "<code>true</code>" or "<code>false</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int show_title_bar=0x7f010002;
        /** <p>Must be one of the following constant values.</p>
<table>
<colgroup align="left" />
<colgroup align="left" />
<colgroup align="left" />
<tr><th>Constant</th><th>Value</th><th>Description</th></tr>
<tr><td><code>standard</code></td><td>0</td><td> Keep in sync with Enums in LikeView </td></tr>
<tr><td><code>button</code></td><td>1</td><td></td></tr>
<tr><td><code>box_count</code></td><td>2</td><td></td></tr>
</table>
         */
        public static final int style=0x7f010014;
        /** <p>Must be a reference to another resource, in the form "<code>@[+][<i>package</i>:]<i>type</i>:<i>name</i></code>"
or to a theme attribute in the form "<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>".
         */
        public static final int title_bar_background=0x7f010005;
        /** <p>Must be a string value, using '\\;' to escape characters such as '\\n' or '\\uxxxx' for a unicode character.
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int title_text=0x7f010003;
    }
    public static final class color {
        public static final int color_picker_background_color=0x7f09000c;
        public static final int color_picker_border_color=0x7f09000b;
        public static final int com_facebook_blue=0x7f090002;
        public static final int com_facebook_likeboxcountview_border_color=0x7f090009;
        public static final int com_facebook_likeboxcountview_text_color=0x7f09000a;
        public static final int com_facebook_likebutton_text_color=0x7f090008;
        public static final int com_facebook_likeview_text_color=0x7f090007;
        public static final int com_facebook_loginview_text_color=0x7f090006;
        public static final int com_facebook_picker_search_bar_background=0x7f090000;
        public static final int com_facebook_picker_search_bar_text=0x7f090001;
        public static final int com_facebook_usersettingsfragment_connected_shadow_color=0x7f090004;
        public static final int com_facebook_usersettingsfragment_connected_text_color=0x7f090003;
        public static final int com_facebook_usersettingsfragment_not_connected_text_color=0x7f090005;
        public static final int dropdown_dark_divider_color=0x7f09000e;
        public static final int dropdown_divider_color=0x7f09000d;
    }
    public static final class dimen {
        public static final int color_button_height=0x7f08001f;
        /** 
         14.5 = Seekbar thumb width - border width, but it depends on the width
	     of the seek bar icon.
    
         */
        public static final int color_picker_gradient_margin=0x7f08001e;
        public static final int com_facebook_likeboxcountview_border_radius=0x7f080015;
        public static final int com_facebook_likeboxcountview_border_width=0x7f080016;
        public static final int com_facebook_likeboxcountview_caret_height=0x7f080014;
        public static final int com_facebook_likeboxcountview_caret_width=0x7f080013;
        public static final int com_facebook_likeboxcountview_text_padding=0x7f080018;
        public static final int com_facebook_likeboxcountview_text_size=0x7f080017;
        public static final int com_facebook_likebutton_compound_drawable_padding=0x7f080011;
        public static final int com_facebook_likebutton_padding_bottom=0x7f080010;
        public static final int com_facebook_likebutton_padding_left=0x7f08000d;
        public static final int com_facebook_likebutton_padding_right=0x7f08000e;
        public static final int com_facebook_likebutton_padding_top=0x7f08000f;
        public static final int com_facebook_likebutton_text_size=0x7f080012;
        public static final int com_facebook_likeview_edge_padding=0x7f08000b;
        public static final int com_facebook_likeview_internal_padding=0x7f08000c;
        public static final int com_facebook_likeview_text_size=0x7f08000a;
        public static final int com_facebook_loginview_compound_drawable_padding=0x7f080008;
        public static final int com_facebook_loginview_padding_bottom=0x7f080007;
        public static final int com_facebook_loginview_padding_left=0x7f080004;
        public static final int com_facebook_loginview_padding_right=0x7f080005;
        public static final int com_facebook_loginview_padding_top=0x7f080006;
        public static final int com_facebook_loginview_text_size=0x7f080009;
        public static final int com_facebook_picker_divider_width=0x7f080001;
        public static final int com_facebook_picker_place_image_size=0x7f080000;
        public static final int com_facebook_profilepictureview_preset_size_large=0x7f08001b;
        public static final int com_facebook_profilepictureview_preset_size_normal=0x7f08001a;
        public static final int com_facebook_profilepictureview_preset_size_small=0x7f080019;
        public static final int com_facebook_tooltip_horizontal_padding=0x7f08001c;
        public static final int com_facebook_usersettingsfragment_profile_picture_height=0x7f080003;
        public static final int com_facebook_usersettingsfragment_profile_picture_width=0x7f080002;
        /** 
         Fallback values if the corresponding com.android.internal.R dimensions
         cannot be retrieved by name.
         Note: Constants taken directly from Android's core/res/values/config.xml.
    
         */
        public static final int config_min_scaling_span=0x7f080022;
        public static final int config_min_scaling_touch_major=0x7f080023;
        public static final int dropdown_item_divider_height=0x7f080021;
        public static final int dropdown_item_height=0x7f080020;
        /**  Link Preview dimensions 
         */
        public static final int link_preview_overlay_radius=0x7f08001d;
    }
    public static final class drawable {
        public static final int bubble=0x7f020000;
        public static final int bubble_arrow_up=0x7f020001;
        public static final int color_button_background=0x7f020002;
        public static final int color_picker_advanced_select_handle=0x7f020003;
        public static final int color_picker_border=0x7f020004;
        public static final int com_facebook_button_blue=0x7f020005;
        public static final int com_facebook_button_blue_focused=0x7f020006;
        public static final int com_facebook_button_blue_normal=0x7f020007;
        public static final int com_facebook_button_blue_pressed=0x7f020008;
        public static final int com_facebook_button_check=0x7f020009;
        public static final int com_facebook_button_check_off=0x7f02000a;
        public static final int com_facebook_button_check_on=0x7f02000b;
        public static final int com_facebook_button_grey_focused=0x7f02000c;
        public static final int com_facebook_button_grey_normal=0x7f02000d;
        public static final int com_facebook_button_grey_pressed=0x7f02000e;
        public static final int com_facebook_button_like=0x7f02000f;
        public static final int com_facebook_button_like_background=0x7f020010;
        public static final int com_facebook_button_like_background_selected=0x7f020011;
        public static final int com_facebook_button_like_icon=0x7f020012;
        public static final int com_facebook_button_like_icon_selected=0x7f020013;
        public static final int com_facebook_button_like_pressed=0x7f020014;
        public static final int com_facebook_button_like_selected=0x7f020015;
        public static final int com_facebook_close=0x7f020016;
        public static final int com_facebook_inverse_icon=0x7f020017;
        public static final int com_facebook_list_divider=0x7f020018;
        public static final int com_facebook_list_section_header_background=0x7f020019;
        public static final int com_facebook_loginbutton_silver=0x7f02001a;
        public static final int com_facebook_logo=0x7f02001b;
        public static final int com_facebook_picker_default_separator_color=0x7f020041;
        public static final int com_facebook_picker_item_background=0x7f02001c;
        public static final int com_facebook_picker_list_focused=0x7f02001d;
        public static final int com_facebook_picker_list_longpressed=0x7f02001e;
        public static final int com_facebook_picker_list_pressed=0x7f02001f;
        public static final int com_facebook_picker_list_selector=0x7f020020;
        public static final int com_facebook_picker_list_selector_background_transition=0x7f020021;
        public static final int com_facebook_picker_list_selector_disabled=0x7f020022;
        public static final int com_facebook_picker_magnifier=0x7f020023;
        public static final int com_facebook_picker_top_button=0x7f020024;
        public static final int com_facebook_place_default_icon=0x7f020025;
        public static final int com_facebook_profile_default_icon=0x7f020026;
        public static final int com_facebook_profile_picture_blank_portrait=0x7f020027;
        public static final int com_facebook_profile_picture_blank_square=0x7f020028;
        public static final int com_facebook_tooltip_black_background=0x7f020029;
        public static final int com_facebook_tooltip_black_bottomnub=0x7f02002a;
        public static final int com_facebook_tooltip_black_topnub=0x7f02002b;
        public static final int com_facebook_tooltip_black_xout=0x7f02002c;
        public static final int com_facebook_tooltip_blue_background=0x7f02002d;
        public static final int com_facebook_tooltip_blue_bottomnub=0x7f02002e;
        public static final int com_facebook_tooltip_blue_topnub=0x7f02002f;
        public static final int com_facebook_tooltip_blue_xout=0x7f020030;
        public static final int com_facebook_top_background=0x7f020031;
        public static final int com_facebook_top_button=0x7f020032;
        public static final int com_facebook_usersettingsfragment_background_gradient=0x7f020033;
        public static final int dropdown_popup_background=0x7f020034;
        public static final int dropdown_popup_background_down=0x7f020035;
        public static final int dropdown_popup_background_up=0x7f020036;
        public static final int ic_action_next_item=0x7f020037;
        public static final int ic_action_previous_item=0x7f020038;
        public static final int ic_action_remove=0x7f020039;
        public static final int ic_menu_search_holo_light=0x7f02003a;
        public static final int ic_menu_share_holo_light=0x7f02003b;
        public static final int icon=0x7f02003c;
        public static final int ondemand_overlay=0x7f02003d;
        public static final int pageinfo_warning_major=0x7f02003e;
        public static final int screen=0x7f02003f;
        public static final int splash=0x7f020040;
    }
    public static final class id {
        public static final int ampm=0x7f070041;
        public static final int appView=0x7f07003a;
        public static final int arrow_image=0x7f070048;
        public static final int bottom=0x7f070006;
        public static final int box_count=0x7f070005;
        public static final int button=0x7f070004;
        public static final int center=0x7f070009;
        public static final int color_button_swatch=0x7f07004b;
        public static final int color_picker_advanced=0x7f070011;
        public static final int color_picker_simple=0x7f070012;
        public static final int com_facebook_body_frame=0x7f07002a;
        public static final int com_facebook_button_xout=0x7f07002c;
        public static final int com_facebook_login_activity_progress_bar=0x7f07001a;
        public static final int com_facebook_picker_activity_circle=0x7f070019;
        public static final int com_facebook_picker_checkbox=0x7f07001c;
        public static final int com_facebook_picker_checkbox_stub=0x7f070020;
        public static final int com_facebook_picker_divider=0x7f070024;
        public static final int com_facebook_picker_done_button=0x7f070023;
        public static final int com_facebook_picker_image=0x7f07001d;
        public static final int com_facebook_picker_list_section_header=0x7f070021;
        public static final int com_facebook_picker_list_view=0x7f070018;
        public static final int com_facebook_picker_profile_pic_stub=0x7f07001e;
        public static final int com_facebook_picker_row_activity_circle=0x7f07001b;
        public static final int com_facebook_picker_search_text=0x7f070029;
        public static final int com_facebook_picker_title=0x7f07001f;
        public static final int com_facebook_picker_title_bar=0x7f070026;
        public static final int com_facebook_picker_title_bar_stub=0x7f070025;
        public static final int com_facebook_picker_top_bar=0x7f070022;
        public static final int com_facebook_search_bar_view=0x7f070028;
        public static final int com_facebook_tooltip_bubble_view_bottom_pointer=0x7f07002e;
        public static final int com_facebook_tooltip_bubble_view_text_body=0x7f07002d;
        public static final int com_facebook_tooltip_bubble_view_top_pointer=0x7f07002b;
        public static final int com_facebook_usersettingsfragment_login_button=0x7f070031;
        public static final int com_facebook_usersettingsfragment_logo_image=0x7f07002f;
        public static final int com_facebook_usersettingsfragment_profile_name=0x7f070030;
        public static final int date_picker=0x7f070032;
        public static final int date_time_suggestion=0x7f070034;
        public static final int date_time_suggestion_label=0x7f070036;
        public static final int date_time_suggestion_value=0x7f070035;
        public static final int dropdown_label=0x7f070038;
        public static final int dropdown_menu_text=0x7f070037;
        public static final int dropdown_popup_window=0x7f07000c;
        public static final int dropdown_sublabel=0x7f070039;
        public static final int gradient=0x7f07000f;
        public static final int gradient_border=0x7f07000e;
        public static final int hour=0x7f07003b;
        public static final int icon_view=0x7f070046;
        public static final int inline=0x7f070007;
        public static final int large=0x7f070002;
        public static final int left=0x7f07000a;
        public static final int main_text=0x7f070049;
        public static final int milli=0x7f070040;
        public static final int minute=0x7f07003c;
        public static final int more_colors_button=0x7f070014;
        public static final int more_colors_button_border=0x7f070013;
        public static final int normal=0x7f070001;
        public static final int picker_subtitle=0x7f070027;
        public static final int pickers=0x7f070042;
        public static final int position_in_year=0x7f070043;
        public static final int right=0x7f07000b;
        public static final int second=0x7f07003e;
        public static final int second_colon=0x7f07003d;
        public static final int second_dot=0x7f07003f;
        public static final int seek_bar=0x7f070010;
        public static final int select_action_menu_copy=0x7f07004e;
        public static final int select_action_menu_cut=0x7f07004d;
        public static final int select_action_menu_paste=0x7f07004f;
        public static final int select_action_menu_select_all=0x7f07004c;
        public static final int select_action_menu_share=0x7f070050;
        public static final int select_action_menu_web_search=0x7f070051;
        public static final int selected_color_view=0x7f070017;
        public static final int selected_color_view_border=0x7f070016;
        public static final int small=0x7f070000;
        public static final int standard=0x7f070003;
        public static final int sub_text=0x7f07004a;
        public static final int text=0x7f07000d;
        public static final int text_wrapper=0x7f070047;
        public static final int time_picker=0x7f070033;
        public static final int title=0x7f070015;
        public static final int top=0x7f070008;
        public static final int top_view=0x7f070045;
        public static final int year=0x7f070044;
    }
    public static final class layout {
        public static final int color_picker_advanced_component=0x7f040000;
        public static final int color_picker_dialog_content=0x7f040001;
        public static final int color_picker_dialog_title=0x7f040002;
        public static final int com_facebook_friendpickerfragment=0x7f040003;
        public static final int com_facebook_login_activity_layout=0x7f040004;
        public static final int com_facebook_picker_activity_circle_row=0x7f040005;
        public static final int com_facebook_picker_checkbox=0x7f040006;
        public static final int com_facebook_picker_image=0x7f040007;
        public static final int com_facebook_picker_list_row=0x7f040008;
        public static final int com_facebook_picker_list_section_header=0x7f040009;
        public static final int com_facebook_picker_search_box=0x7f04000a;
        public static final int com_facebook_picker_title_bar=0x7f04000b;
        public static final int com_facebook_picker_title_bar_stub=0x7f04000c;
        public static final int com_facebook_placepickerfragment=0x7f04000d;
        public static final int com_facebook_placepickerfragment_list_row=0x7f04000e;
        public static final int com_facebook_search_bar_layout=0x7f04000f;
        public static final int com_facebook_tooltip_bubble=0x7f040010;
        public static final int com_facebook_usersettingsfragment=0x7f040011;
        public static final int date_time_picker_dialog=0x7f040012;
        public static final int date_time_suggestion=0x7f040013;
        public static final int dropdown_item=0x7f040014;
        public static final int main=0x7f040015;
        public static final int multi_field_time_picker_dialog=0x7f040016;
        public static final int two_field_date_picker=0x7f040017;
        public static final int validation_message_bubble=0x7f040018;
    }
    public static final class menu {
        public static final int select_action_menu=0x7f0d0000;
    }
    public static final class mipmap {
        public static final int app_icon=0x7f030000;
    }
    public static final class raw {
        public static final int contacts_api=0x7f060000;
        public static final int device_capabilities_api=0x7f060001;
        public static final int icudtl=0x7f060002;
        public static final int launch_screen_api=0x7f060003;
        public static final int messaging_api=0x7f060004;
        public static final int presentation_api=0x7f060005;
        public static final int xwalk=0x7f060006;
    }
    public static final class string {
        public static final int accessibility_content_view=0x7f0a001f;
        public static final int accessibility_date_picker_month=0x7f0a002f;
        public static final int accessibility_date_picker_week=0x7f0a0030;
        public static final int accessibility_date_picker_year=0x7f0a0031;
        public static final int accessibility_datetime_picker_date=0x7f0a002d;
        public static final int accessibility_datetime_picker_time=0x7f0a002e;
        public static final int accessibility_time_picker_ampm=0x7f0a0036;
        public static final int accessibility_time_picker_hour=0x7f0a0032;
        public static final int accessibility_time_picker_milli=0x7f0a0035;
        public static final int accessibility_time_picker_minute=0x7f0a0033;
        public static final int accessibility_time_picker_second=0x7f0a0034;
        public static final int actionbar_share=0x7f0a001d;
        public static final int actionbar_web_search=0x7f0a001e;
        public static final int app_name=0x7f0a0063;
        public static final int color_picker_button_black=0x7f0a004f;
        public static final int color_picker_button_blue=0x7f0a004b;
        public static final int color_picker_button_cancel=0x7f0a0047;
        public static final int color_picker_button_cyan=0x7f0a004a;
        public static final int color_picker_button_green=0x7f0a004c;
        public static final int color_picker_button_magenta=0x7f0a004d;
        public static final int color_picker_button_more=0x7f0a0042;
        public static final int color_picker_button_red=0x7f0a0049;
        public static final int color_picker_button_set=0x7f0a0046;
        public static final int color_picker_button_white=0x7f0a0050;
        public static final int color_picker_button_yellow=0x7f0a004e;
        public static final int color_picker_dialog_title=0x7f0a0048;
        public static final int color_picker_hue=0x7f0a0043;
        public static final int color_picker_saturation=0x7f0a0044;
        public static final int color_picker_value=0x7f0a0045;
        public static final int com_facebook_choose_friends=0x7f0a0011;
        public static final int com_facebook_dialogloginactivity_ok_button=0x7f0a0000;
        public static final int com_facebook_image_download_unknown_error=0x7f0a001c;
        public static final int com_facebook_internet_permission_error_message=0x7f0a0015;
        public static final int com_facebook_internet_permission_error_title=0x7f0a0014;
        public static final int com_facebook_like_button_liked=0x7f0a0002;
        public static final int com_facebook_like_button_not_liked=0x7f0a0001;
        public static final int com_facebook_loading=0x7f0a0013;
        public static final int com_facebook_loginview_cancel_action=0x7f0a0008;
        public static final int com_facebook_loginview_log_in_button=0x7f0a0004;
        public static final int com_facebook_loginview_log_out_action=0x7f0a0007;
        public static final int com_facebook_loginview_log_out_button=0x7f0a0003;
        public static final int com_facebook_loginview_logged_in_as=0x7f0a0005;
        public static final int com_facebook_loginview_logged_in_using_facebook=0x7f0a0006;
        public static final int com_facebook_logo_content_description=0x7f0a0009;
        public static final int com_facebook_nearby=0x7f0a0012;
        public static final int com_facebook_picker_done_button_text=0x7f0a0010;
        public static final int com_facebook_placepicker_subtitle_catetory_only_format=0x7f0a000e;
        public static final int com_facebook_placepicker_subtitle_format=0x7f0a000d;
        public static final int com_facebook_placepicker_subtitle_were_here_only_format=0x7f0a000f;
        public static final int com_facebook_requesterror_password_changed=0x7f0a0018;
        public static final int com_facebook_requesterror_permissions=0x7f0a001a;
        public static final int com_facebook_requesterror_reconnect=0x7f0a0019;
        public static final int com_facebook_requesterror_relogin=0x7f0a0017;
        public static final int com_facebook_requesterror_web_login=0x7f0a0016;
        public static final int com_facebook_tooltip_default=0x7f0a001b;
        public static final int com_facebook_usersettingsfragment_log_in_button=0x7f0a000a;
        public static final int com_facebook_usersettingsfragment_logged_in=0x7f0a000b;
        public static final int com_facebook_usersettingsfragment_not_logged_in=0x7f0a000c;
        public static final int copy_to_clipboard_failure_message=0x7f0a0051;
        public static final int cpu_arch_mismatch_message=0x7f0a0060;
        public static final int cpu_arch_mismatch_title=0x7f0a005f;
        public static final int date_picker_dialog_clear=0x7f0a0022;
        public static final int date_picker_dialog_other_button_label=0x7f0a0023;
        public static final int date_picker_dialog_set=0x7f0a0021;
        public static final int date_picker_dialog_title=0x7f0a0020;
        public static final int date_time_picker_dialog_title=0x7f0a0024;
        public static final int download_already_exists_toast=0x7f0a0057;
        public static final int download_failed_toast=0x7f0a0058;
        public static final int download_finished_toast=0x7f0a0059;
        public static final int download_no_permission_toast=0x7f0a0056;
        public static final int download_start_toast=0x7f0a0055;
        public static final int fb_app_id=0x7f0a0065;
        public static final int fb_app_name=0x7f0a0066;
        public static final int go=0x7f0a0064;
        public static final int goto_store_button_label=0x7f0a0061;
        public static final int http_auth_log_in=0x7f0a005e;
        public static final int http_auth_password=0x7f0a005d;
        public static final int http_auth_title=0x7f0a005b;
        public static final int http_auth_user_name=0x7f0a005c;
        public static final int js_alert_title=0x7f0a0052;
        public static final int js_confirm_title=0x7f0a0053;
        public static final int js_prompt_title=0x7f0a0054;
        public static final int low_memory_error=0x7f0a0040;
        public static final int media_player_error_button=0x7f0a003a;
        public static final int media_player_error_text_invalid_progressive_playback=0x7f0a0038;
        public static final int media_player_error_text_unknown=0x7f0a0039;
        public static final int media_player_error_title=0x7f0a0037;
        public static final int media_player_loading_video=0x7f0a003b;
        public static final int month_picker_dialog_title=0x7f0a002b;
        public static final int opening_file_error=0x7f0a0041;
        public static final int profiler_error_toast=0x7f0a003f;
        public static final int profiler_no_storage_toast=0x7f0a003e;
        public static final int profiler_started_toast=0x7f0a003c;
        public static final int profiler_stopped_toast=0x7f0a003d;
        public static final int report_feedback_button_label=0x7f0a0062;
        public static final int ssl_alert_title=0x7f0a005a;
        public static final int time_picker_dialog_am=0x7f0a0026;
        public static final int time_picker_dialog_hour_minute_separator=0x7f0a0028;
        public static final int time_picker_dialog_minute_second_separator=0x7f0a0029;
        public static final int time_picker_dialog_pm=0x7f0a0027;
        public static final int time_picker_dialog_second_subsecond_separator=0x7f0a002a;
        public static final int time_picker_dialog_title=0x7f0a0025;
        public static final int week_picker_dialog_title=0x7f0a002c;
    }
    public static final class style {
        public static final int DropdownPopupWindow=0x7f0b0004;
        public static final int SelectPopupDialog=0x7f0b0003;
        public static final int com_facebook_loginview_default_style=0x7f0b0000;
        public static final int com_facebook_loginview_silver_style=0x7f0b0001;
        public static final int tooltip_bubble_text=0x7f0b0002;
    }
    public static final class xml {
        public static final int config=0x7f050000;
    }
    public static final class styleable {
        /** Attributes that can be used with a com_facebook_friend_picker_fragment.
           <p>Includes the following attributes:</p>
           <table>
           <colgroup align="left" />
           <colgroup align="left" />
           <tr><th>Attribute</th><th>Description</th></tr>
           <tr><td><code>{@link #com_facebook_friend_picker_fragment_multi_select com.ionicframework.goodmood362235:multi_select}</code></td><td></td></tr>
           </table>
           @see #com_facebook_friend_picker_fragment_multi_select
         */
        public static final int[] com_facebook_friend_picker_fragment = {
            0x7f010007
        };
        /**
          <p>This symbol is the offset where the {@link com.ionicframework.goodmood362235.R.attr#multi_select}
          attribute's value can be found in the {@link #com_facebook_friend_picker_fragment} array.


          <p>Must be a boolean value, either "<code>true</code>" or "<code>false</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name com.ionicframework.goodmood362235:multi_select
        */
        public static final int com_facebook_friend_picker_fragment_multi_select = 0;
        /** Attributes that can be used with a com_facebook_like_view.
           <p>Includes the following attributes:</p>
           <table>
           <colgroup align="left" />
           <colgroup align="left" />
           <tr><th>Attribute</th><th>Description</th></tr>
           <tr><td><code>{@link #com_facebook_like_view_auxiliary_view_position com.ionicframework.goodmood362235:auxiliary_view_position}</code></td><td></td></tr>
           <tr><td><code>{@link #com_facebook_like_view_foreground_color com.ionicframework.goodmood362235:foreground_color}</code></td><td></td></tr>
           <tr><td><code>{@link #com_facebook_like_view_horizontal_alignment com.ionicframework.goodmood362235:horizontal_alignment}</code></td><td></td></tr>
           <tr><td><code>{@link #com_facebook_like_view_object_id com.ionicframework.goodmood362235:object_id}</code></td><td></td></tr>
           <tr><td><code>{@link #com_facebook_like_view_style com.ionicframework.goodmood362235:style}</code></td><td></td></tr>
           </table>
           @see #com_facebook_like_view_auxiliary_view_position
           @see #com_facebook_like_view_foreground_color
           @see #com_facebook_like_view_horizontal_alignment
           @see #com_facebook_like_view_object_id
           @see #com_facebook_like_view_style
         */
        public static final int[] com_facebook_like_view = {
            0x7f010012, 0x7f010013, 0x7f010014, 0x7f010015,
            0x7f010016
        };
        /**
          <p>This symbol is the offset where the {@link com.ionicframework.goodmood362235.R.attr#auxiliary_view_position}
          attribute's value can be found in the {@link #com_facebook_like_view} array.


          <p>Must be one of the following constant values.</p>
<table>
<colgroup align="left" />
<colgroup align="left" />
<colgroup align="left" />
<tr><th>Constant</th><th>Value</th><th>Description</th></tr>
<tr><td><code>bottom</code></td><td>0</td><td> Keep in sync with Enums in LikeView </td></tr>
<tr><td><code>inline</code></td><td>1</td><td></td></tr>
<tr><td><code>top</code></td><td>2</td><td></td></tr>
</table>
          @attr name com.ionicframework.goodmood362235:auxiliary_view_position
        */
        public static final int com_facebook_like_view_auxiliary_view_position = 3;
        /**
          <p>This symbol is the offset where the {@link com.ionicframework.goodmood362235.R.attr#foreground_color}
          attribute's value can be found in the {@link #com_facebook_like_view} array.


          <p>Must be a color value, in the form of "<code>#<i>rgb</i></code>", "<code>#<i>argb</i></code>",
"<code>#<i>rrggbb</i></code>", or "<code>#<i>aarrggbb</i></code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name com.ionicframework.goodmood362235:foreground_color
        */
        public static final int com_facebook_like_view_foreground_color = 0;
        /**
          <p>This symbol is the offset where the {@link com.ionicframework.goodmood362235.R.attr#horizontal_alignment}
          attribute's value can be found in the {@link #com_facebook_like_view} array.


          <p>Must be one of the following constant values.</p>
<table>
<colgroup align="left" />
<colgroup align="left" />
<colgroup align="left" />
<tr><th>Constant</th><th>Value</th><th>Description</th></tr>
<tr><td><code>center</code></td><td>0</td><td> Keep in sync with Enums in LikeView </td></tr>
<tr><td><code>left</code></td><td>1</td><td></td></tr>
<tr><td><code>right</code></td><td>2</td><td></td></tr>
</table>
          @attr name com.ionicframework.goodmood362235:horizontal_alignment
        */
        public static final int com_facebook_like_view_horizontal_alignment = 4;
        /**
          <p>This symbol is the offset where the {@link com.ionicframework.goodmood362235.R.attr#object_id}
          attribute's value can be found in the {@link #com_facebook_like_view} array.


          <p>Must be a string value, using '\\;' to escape characters such as '\\n' or '\\uxxxx' for a unicode character.
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name com.ionicframework.goodmood362235:object_id
        */
        public static final int com_facebook_like_view_object_id = 1;
        /**
          <p>This symbol is the offset where the {@link com.ionicframework.goodmood362235.R.attr#style}
          attribute's value can be found in the {@link #com_facebook_like_view} array.


          <p>Must be one of the following constant values.</p>
<table>
<colgroup align="left" />
<colgroup align="left" />
<colgroup align="left" />
<tr><th>Constant</th><th>Value</th><th>Description</th></tr>
<tr><td><code>standard</code></td><td>0</td><td> Keep in sync with Enums in LikeView </td></tr>
<tr><td><code>button</code></td><td>1</td><td></td></tr>
<tr><td><code>box_count</code></td><td>2</td><td></td></tr>
</table>
          @attr name com.ionicframework.goodmood362235:style
        */
        public static final int com_facebook_like_view_style = 2;
        /** Attributes that can be used with a com_facebook_login_view.
           <p>Includes the following attributes:</p>
           <table>
           <colgroup align="left" />
           <colgroup align="left" />
           <tr><th>Attribute</th><th>Description</th></tr>
           <tr><td><code>{@link #com_facebook_login_view_confirm_logout com.ionicframework.goodmood362235:confirm_logout}</code></td><td></td></tr>
           <tr><td><code>{@link #com_facebook_login_view_fetch_user_info com.ionicframework.goodmood362235:fetch_user_info}</code></td><td></td></tr>
           <tr><td><code>{@link #com_facebook_login_view_login_text com.ionicframework.goodmood362235:login_text}</code></td><td></td></tr>
           <tr><td><code>{@link #com_facebook_login_view_logout_text com.ionicframework.goodmood362235:logout_text}</code></td><td></td></tr>
           </table>
           @see #com_facebook_login_view_confirm_logout
           @see #com_facebook_login_view_fetch_user_info
           @see #com_facebook_login_view_login_text
           @see #com_facebook_login_view_logout_text
         */
        public static final int[] com_facebook_login_view = {
            0x7f01000c, 0x7f01000d, 0x7f01000e, 0x7f01000f
        };
        /**
          <p>This symbol is the offset where the {@link com.ionicframework.goodmood362235.R.attr#confirm_logout}
          attribute's value can be found in the {@link #com_facebook_login_view} array.


          <p>Must be a boolean value, either "<code>true</code>" or "<code>false</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name com.ionicframework.goodmood362235:confirm_logout
        */
        public static final int com_facebook_login_view_confirm_logout = 0;
        /**
          <p>This symbol is the offset where the {@link com.ionicframework.goodmood362235.R.attr#fetch_user_info}
          attribute's value can be found in the {@link #com_facebook_login_view} array.


          <p>Must be a boolean value, either "<code>true</code>" or "<code>false</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name com.ionicframework.goodmood362235:fetch_user_info
        */
        public static final int com_facebook_login_view_fetch_user_info = 1;
        /**
          <p>This symbol is the offset where the {@link com.ionicframework.goodmood362235.R.attr#login_text}
          attribute's value can be found in the {@link #com_facebook_login_view} array.


          <p>Must be a string value, using '\\;' to escape characters such as '\\n' or '\\uxxxx' for a unicode character.
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name com.ionicframework.goodmood362235:login_text
        */
        public static final int com_facebook_login_view_login_text = 2;
        /**
          <p>This symbol is the offset where the {@link com.ionicframework.goodmood362235.R.attr#logout_text}
          attribute's value can be found in the {@link #com_facebook_login_view} array.


          <p>Must be a string value, using '\\;' to escape characters such as '\\n' or '\\uxxxx' for a unicode character.
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name com.ionicframework.goodmood362235:logout_text
        */
        public static final int com_facebook_login_view_logout_text = 3;
        /** Attributes that can be used with a com_facebook_picker_fragment.
           <p>Includes the following attributes:</p>
           <table>
           <colgroup align="left" />
           <colgroup align="left" />
           <tr><th>Attribute</th><th>Description</th></tr>
           <tr><td><code>{@link #com_facebook_picker_fragment_done_button_background com.ionicframework.goodmood362235:done_button_background}</code></td><td></td></tr>
           <tr><td><code>{@link #com_facebook_picker_fragment_done_button_text com.ionicframework.goodmood362235:done_button_text}</code></td><td></td></tr>
           <tr><td><code>{@link #com_facebook_picker_fragment_extra_fields com.ionicframework.goodmood362235:extra_fields}</code></td><td></td></tr>
           <tr><td><code>{@link #com_facebook_picker_fragment_show_pictures com.ionicframework.goodmood362235:show_pictures}</code></td><td></td></tr>
           <tr><td><code>{@link #com_facebook_picker_fragment_show_title_bar com.ionicframework.goodmood362235:show_title_bar}</code></td><td></td></tr>
           <tr><td><code>{@link #com_facebook_picker_fragment_title_bar_background com.ionicframework.goodmood362235:title_bar_background}</code></td><td></td></tr>
           <tr><td><code>{@link #com_facebook_picker_fragment_title_text com.ionicframework.goodmood362235:title_text}</code></td><td></td></tr>
           </table>
           @see #com_facebook_picker_fragment_done_button_background
           @see #com_facebook_picker_fragment_done_button_text
           @see #com_facebook_picker_fragment_extra_fields
           @see #com_facebook_picker_fragment_show_pictures
           @see #com_facebook_picker_fragment_show_title_bar
           @see #com_facebook_picker_fragment_title_bar_background
           @see #com_facebook_picker_fragment_title_text
         */
        public static final int[] com_facebook_picker_fragment = {
            0x7f010000, 0x7f010001, 0x7f010002, 0x7f010003,
            0x7f010004, 0x7f010005, 0x7f010006
        };
        /**
          <p>This symbol is the offset where the {@link com.ionicframework.goodmood362235.R.attr#done_button_background}
          attribute's value can be found in the {@link #com_facebook_picker_fragment} array.


          <p>Must be a reference to another resource, in the form "<code>@[+][<i>package</i>:]<i>type</i>:<i>name</i></code>"
or to a theme attribute in the form "<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>".
          @attr name com.ionicframework.goodmood362235:done_button_background
        */
        public static final int com_facebook_picker_fragment_done_button_background = 6;
        /**
          <p>This symbol is the offset where the {@link com.ionicframework.goodmood362235.R.attr#done_button_text}
          attribute's value can be found in the {@link #com_facebook_picker_fragment} array.


          <p>Must be a string value, using '\\;' to escape characters such as '\\n' or '\\uxxxx' for a unicode character.
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name com.ionicframework.goodmood362235:done_button_text
        */
        public static final int com_facebook_picker_fragment_done_button_text = 4;
        /**
          <p>This symbol is the offset where the {@link com.ionicframework.goodmood362235.R.attr#extra_fields}
          attribute's value can be found in the {@link #com_facebook_picker_fragment} array.


          <p>Must be a string value, using '\\;' to escape characters such as '\\n' or '\\uxxxx' for a unicode character.
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name com.ionicframework.goodmood362235:extra_fields
        */
        public static final int com_facebook_picker_fragment_extra_fields = 1;
        /**
          <p>This symbol is the offset where the {@link com.ionicframework.goodmood362235.R.attr#show_pictures}
          attribute's value can be found in the {@link #com_facebook_picker_fragment} array.


          <p>Must be a boolean value, either "<code>true</code>" or "<code>false</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name com.ionicframework.goodmood362235:show_pictures
        */
        public static final int com_facebook_picker_fragment_show_pictures = 0;
        /**
          <p>This symbol is the offset where the {@link com.ionicframework.goodmood362235.R.attr#show_title_bar}
          attribute's value can be found in the {@link #com_facebook_picker_fragment} array.


          <p>Must be a boolean value, either "<code>true</code>" or "<code>false</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name com.ionicframework.goodmood362235:show_title_bar
        */
        public static final int com_facebook_picker_fragment_show_title_bar = 2;
        /**
          <p>This symbol is the offset where the {@link com.ionicframework.goodmood362235.R.attr#title_bar_background}
          attribute's value can be found in the {@link #com_facebook_picker_fragment} array.


          <p>Must be a reference to another resource, in the form "<code>@[+][<i>package</i>:]<i>type</i>:<i>name</i></code>"
or to a theme attribute in the form "<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>".
          @attr name com.ionicframework.goodmood362235:title_bar_background
        */
        public static final int com_facebook_picker_fragment_title_bar_background = 5;
        /**
          <p>This symbol is the offset where the {@link com.ionicframework.goodmood362235.R.attr#title_text}
          attribute's value can be found in the {@link #com_facebook_picker_fragment} array.


          <p>Must be a string value, using '\\;' to escape characters such as '\\n' or '\\uxxxx' for a unicode character.
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name com.ionicframework.goodmood362235:title_text
        */
        public static final int com_facebook_picker_fragment_title_text = 3;
        /** Attributes that can be used with a com_facebook_place_picker_fragment.
           <p>Includes the following attributes:</p>
           <table>
           <colgroup align="left" />
           <colgroup align="left" />
           <tr><th>Attribute</th><th>Description</th></tr>
           <tr><td><code>{@link #com_facebook_place_picker_fragment_radius_in_meters com.ionicframework.goodmood362235:radius_in_meters}</code></td><td></td></tr>
           <tr><td><code>{@link #com_facebook_place_picker_fragment_results_limit com.ionicframework.goodmood362235:results_limit}</code></td><td></td></tr>
           <tr><td><code>{@link #com_facebook_place_picker_fragment_search_text com.ionicframework.goodmood362235:search_text}</code></td><td></td></tr>
           <tr><td><code>{@link #com_facebook_place_picker_fragment_show_search_box com.ionicframework.goodmood362235:show_search_box}</code></td><td></td></tr>
           </table>
           @see #com_facebook_place_picker_fragment_radius_in_meters
           @see #com_facebook_place_picker_fragment_results_limit
           @see #com_facebook_place_picker_fragment_search_text
           @see #com_facebook_place_picker_fragment_show_search_box
         */
        public static final int[] com_facebook_place_picker_fragment = {
            0x7f010008, 0x7f010009, 0x7f01000a, 0x7f01000b
        };
        /**
          <p>This symbol is the offset where the {@link com.ionicframework.goodmood362235.R.attr#radius_in_meters}
          attribute's value can be found in the {@link #com_facebook_place_picker_fragment} array.


          <p>Must be an integer value, such as "<code>100</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name com.ionicframework.goodmood362235:radius_in_meters
        */
        public static final int com_facebook_place_picker_fragment_radius_in_meters = 0;
        /**
          <p>This symbol is the offset where the {@link com.ionicframework.goodmood362235.R.attr#results_limit}
          attribute's value can be found in the {@link #com_facebook_place_picker_fragment} array.


          <p>Must be an integer value, such as "<code>100</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name com.ionicframework.goodmood362235:results_limit
        */
        public static final int com_facebook_place_picker_fragment_results_limit = 1;
        /**
          <p>This symbol is the offset where the {@link com.ionicframework.goodmood362235.R.attr#search_text}
          attribute's value can be found in the {@link #com_facebook_place_picker_fragment} array.


          <p>Must be a string value, using '\\;' to escape characters such as '\\n' or '\\uxxxx' for a unicode character.
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name com.ionicframework.goodmood362235:search_text
        */
        public static final int com_facebook_place_picker_fragment_search_text = 2;
        /**
          <p>This symbol is the offset where the {@link com.ionicframework.goodmood362235.R.attr#show_search_box}
          attribute's value can be found in the {@link #com_facebook_place_picker_fragment} array.


          <p>Must be a boolean value, either "<code>true</code>" or "<code>false</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name com.ionicframework.goodmood362235:show_search_box
        */
        public static final int com_facebook_place_picker_fragment_show_search_box = 3;
        /** Attributes that can be used with a com_facebook_profile_picture_view.
           <p>Includes the following attributes:</p>
           <table>
           <colgroup align="left" />
           <colgroup align="left" />
           <tr><th>Attribute</th><th>Description</th></tr>
           <tr><td><code>{@link #com_facebook_profile_picture_view_is_cropped com.ionicframework.goodmood362235:is_cropped}</code></td><td></td></tr>
           <tr><td><code>{@link #com_facebook_profile_picture_view_preset_size com.ionicframework.goodmood362235:preset_size}</code></td><td></td></tr>
           </table>
           @see #com_facebook_profile_picture_view_is_cropped
           @see #com_facebook_profile_picture_view_preset_size
         */
        public static final int[] com_facebook_profile_picture_view = {
            0x7f010010, 0x7f010011
        };
        /**
          <p>This symbol is the offset where the {@link com.ionicframework.goodmood362235.R.attr#is_cropped}
          attribute's value can be found in the {@link #com_facebook_profile_picture_view} array.


          <p>Must be a boolean value, either "<code>true</code>" or "<code>false</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name com.ionicframework.goodmood362235:is_cropped
        */
        public static final int com_facebook_profile_picture_view_is_cropped = 1;
        /**
          <p>This symbol is the offset where the {@link com.ionicframework.goodmood362235.R.attr#preset_size}
          attribute's value can be found in the {@link #com_facebook_profile_picture_view} array.


          <p>Must be one of the following constant values.</p>
<table>
<colgroup align="left" />
<colgroup align="left" />
<colgroup align="left" />
<tr><th>Constant</th><th>Value</th><th>Description</th></tr>
<tr><td><code>small</code></td><td>-2</td><td> Keep in sync with constants in ProfilePictureView </td></tr>
<tr><td><code>normal</code></td><td>-3</td><td></td></tr>
<tr><td><code>large</code></td><td>-4</td><td></td></tr>
</table>
          @attr name com.ionicframework.goodmood362235:preset_size
        */
        public static final int com_facebook_profile_picture_view_preset_size = 0;
    };
}
